name: Test Suite

on:
  pull_request:
    branches: ["main"]

env:
  NODE_VERSION: "20.x"

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Unit Tests
        run: npm test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-and-integration-tests
    steps:
      - name: Run E2E Tests
        run: npx cypress run
