name: Test Suite

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


env:
  AZURE_RESOURCE_GROUP: eirik.imrik_rg_1308
  AZURE_WEBAPP_NAME: eirik-app
  NODE_VERSION: "20.x"

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

  e2e-tests:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        run: npx cypress run

  infrastructure-tests:
    name: Run Infrastructure Tests
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Web App Status
        run: |
          app_state=$(az webapp show --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --query state -o tsv)
          if [ "$app_state" != "Running" ]; then
              echo "Web App is not running"
              exit 1
          fi

      - name: Validate ARM Template
        run: |
          az deployment group validate \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file template.json